import React, { useState, useContext, useMemo, useEffect, useCallback } from 'react';
import {
    View, Text, StyleSheet, FlatList, TouchableOpacity,
    ActivityIndicator, Alert, StatusBar, TextInput, Linking, RefreshControl, ScrollView
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { MaterialCommunityIcons } from '@expo/vector-icons';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import axios from 'axios';
import { UserContext } from '../../services/UserContext';
import API_URL from '../../services/apiconfig';
import Toast from 'react-native-toast-message';

const StatementScreen = ({ route, navigation }) => {
    const { user } = useContext(UserContext);
    const { tenantBreakdown = [], startDate, endDate } = route.params || {};

    const adminId = user?._id || user?.id;

    // --- States ---
    const [searchText, setSearchText] = useState('');
    const [history, setHistory] = useState([]);
    const [loadingHistory, setLoadingHistory] = useState(true);
    const [actionLoading, setActionLoading] = useState(null); // specific task loading

    const today = new Date().toLocaleDateString('en-IN');

    // 🔄 Fetch Saved History from DB
    const fetchHistory = useCallback(async () => {
        if (!adminId) return;
        try {
            const res = await axios.get(`${API_URL}/statement/history/${adminId}`);
            setHistory(res.data);
        } catch (e) {
            console.log("History fetch failed");
        } finally {
            setLoadingHistory(false);
        }
    }, [adminId]);

    useEffect(() => {
        fetchHistory();
    }, [fetchHistory]);

    // 🔍 Unified Search Logic (Filters both Current & History)
    const filteredCurrent = useMemo(() => {
        return tenantBreakdown.filter(t => t.tenantName.toLowerCase().includes(searchText.toLowerCase()));
    }, [searchText, tenantBreakdown]);

    const filteredHistory = useMemo(() => {
        return history.filter(h => h.tenantName.toLowerCase().includes(searchText.toLowerCase()));
    }, [searchText, history]);

    // 📄 HTML Generator
    const createHTML = (item) => `
    <html>
      <body style="font-family: Helvetica; padding: 40px; color: #333;">
        <h1 style="color: #333399; text-align: center;">${user.companyName}</h1>
        <h2 style="text-align: center; border-bottom: 1px solid #ddd; padding-bottom: 10px;">ELECTRICITY INVOICE</h2>
        <div style="margin-top: 20px;">
            <p><b>Tenant:</b> ${item.tenantName}</p>
            <p><b>Meter ID:</b> ${item.meterId}</p>
            <p><b>Date:</b> ${today}</p>
        </div>
        <table style="width: 100%; border-collapse: collapse; margin-top: 20px;">
            <tr style="background: #f2f2f2;">
                <th style="padding: 10px; border: 1px solid #ddd; text-align: left;">Description</th>
                <th style="padding: 10px; border: 1px solid #ddd; text-align: right;">Amount</th>
            </tr>
            <tr>
                <td style="padding: 10px; border: 1px solid #ddd;">Total Consumption (${item.units} units)</td>
                <td style="padding: 10px; border: 1px solid #ddd; text-align: right;">₹${item.totalBill || item.totalAmount}</td>
            </tr>
        </table>
        <div style="margin-top: 30px; text-align: center; font-size: 12px; color: #777;">
            <p>Generated by Property Manager App</p>
        </div>
      </body>
    </html>
    `;

    // 💾 Save and Refresh History
    const handleSaveStatement = async (item) => {
        setActionLoading(item.tenantId);
        try {
            const html = createHTML(item);
            await axios.post(`${API_URL}/statement/save`, {
                adminId,
                tenantId: item.tenantId,
                tenantName: item.tenantName,
                meterId: item.meterId,
                periodFrom: startDate,
                periodTo: endDate,
                units: item.units,
                totalAmount: item.totalBill,
                htmlContent: html
            });
            Toast.show({ type: 'success', text1: 'Saved to History ✅' });
            fetchHistory(); // Refresh the history list instantly
        } catch (e) {
            Alert.alert("Error", "Could not save statement");
        } finally {
            setActionLoading(null);
        }
    };

    const handleView = async (item) => {
        try {
            const html = createHTML(item);
            await Print.printAsync({ html });
        } catch (e) { Alert.alert("Error", "Could not open preview"); }
    };

    const renderHeader = () => (
        <View style={{ paddingBottom: 10 }}>
            {/* CURRENT LIST SECTION */}
            {filteredCurrent.length > 0 && (
                <>
                    <View style={styles.sectionHeader}>
                        <Text style={styles.sectionTitle}>Ready for Billing</Text>
                        <View style={styles.badge}><Text style={styles.badgeText}>{filteredCurrent.length}</Text></View>
                    </View>
                    {filteredCurrent.map((item) => (
                        <View key={item.tenantId} style={styles.card}>
                            <View style={styles.cardInfo}>
                                <Text style={styles.tName}>{item.tenantName}</Text>
                                <Text style={styles.tSub}>₹{item.totalBill.toFixed(2)} • {item.units} kWh</Text>
                            </View>
                            <View style={styles.actionRow}>
                                <TouchableOpacity onPress={() => handleView(item)} style={styles.iconBtn}>
                                    <MaterialCommunityIcons name="eye-outline" size={24} color="#333399" />
                                </TouchableOpacity>
                                <TouchableOpacity 
                                    onPress={() => handleSaveStatement(item)} 
                                    style={[styles.iconBtn, { backgroundColor: '#E8F5E9' }]}
                                    disabled={actionLoading === item.tenantId}
                                >
                                    {actionLoading === item.tenantId ? (
                                        <ActivityIndicator size="small" color="#4CAF50" />
                                    ) : (
                                        <MaterialCommunityIcons name="content-save-move" size={24} color="#4CAF50" />
                                    )}
                                </TouchableOpacity>
                            </View>
                        </View>
                    ))}
                </>
            )}

            {/* SAVED HISTORY SECTION */}
            <View style={[styles.sectionHeader, { marginTop: 20 }]}>
                <Text style={styles.sectionTitle}>Saved History</Text>
                <MaterialCommunityIcons name="history" size={20} color="#666" />
            </View>
        </View>
    );

    return (
        <SafeAreaView style={styles.container}>
            <StatusBar barStyle="dark-content" />
            
            {/* SEARCH HEADER */}
            <View style={styles.header}>
                <TouchableOpacity onPress={() => navigation.goBack()} style={styles.backBtn}>
                    <MaterialCommunityIcons name="chevron-left" size={32} color="#333" />
                </TouchableOpacity>
                <View style={styles.searchBox}>
                    <MaterialCommunityIcons name="magnify" size={20} color="#999" />
                    <TextInput 
                        placeholder="Search invoices..." 
                        style={styles.searchInput}
                        value={searchText}
                        onChangeText={setSearchText}
                    />
                </View>
            </View>

            <FlatList
                data={filteredHistory}
                keyExtractor={(item) => item._id}
                ListHeaderComponent={renderHeader}
                contentContainerStyle={{ padding: 16 }}
                refreshControl={<RefreshControl refreshing={loadingHistory} onRefresh={fetchHistory} />}
                renderItem={({ item }) => (
                    <View style={styles.historyCard}>
                        <View style={styles.cardInfo}>
                            <View style={styles.nameRow}>
                                <Text style={styles.hName}>{item.tenantName}</Text>
                                <View style={styles.dateTag}>
                                    <Text style={styles.dateTagText}>
                                        {new Date(item.periodTo).toLocaleDateString('en-IN', {month:'short', day:'2-digit'})}
                                    </Text>
                                </View>
                            </View>
                            <Text style={styles.tSub}>Total: ₹{item.totalAmount} • {item.units} kWh</Text>
                        </View>
                        <TouchableOpacity onPress={() => Linking.openURL(item.pdfUrl)} style={styles.pdfBtn}>
                            <MaterialCommunityIcons name="file-pdf-box" size={30} color="#DC2626" />
                        </TouchableOpacity>
                    </View>
                )}
                ListEmptyComponent={!loadingHistory && <Text style={styles.empty}>No statements found.</Text>}
            />
        </SafeAreaView>
    );
};

const styles = StyleSheet.create({
    container: { flex: 1, backgroundColor: '#F9FAFB' },
    header: { flexDirection: 'row', alignItems: 'center', padding: 15, backgroundColor: '#FFF', elevation: 2 },
    backBtn: { marginRight: 10 },
    searchBox: { flex: 1, flexDirection: 'row', backgroundColor: '#F1F3F6', borderRadius: 12, paddingHorizontal: 12, height: 45, alignItems: 'center' },
    searchInput: { flex: 1, marginLeft: 8, fontSize: 14, fontWeight: '500' },
    
    sectionHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 12, paddingHorizontal: 5 },
    sectionTitle: { fontSize: 16, fontWeight: '800', color: '#4B5563', marginRight: 10 },
    badge: { backgroundColor: '#333399', borderRadius: 10, paddingHorizontal: 8, paddingVertical: 2 },
    badgeText: { color: '#FFF', fontSize: 10, fontWeight: 'bold' },

    card: { flexDirection: 'row', backgroundColor: '#FFF', padding: 16, borderRadius: 18, marginBottom: 10, alignItems: 'center', elevation: 2 },
    historyCard: { flexDirection: 'row', backgroundColor: '#F3F4F6', padding: 16, borderRadius: 18, marginBottom: 10, alignItems: 'center', borderLeftWidth: 4, borderLeftColor: '#DC2626' },
    
    cardInfo: { flex: 1 },
    nameRow: { flexDirection: 'row', alignItems: 'center' },
    tName: { fontSize: 15, fontWeight: 'bold', color: '#1F2937' },
    hName: { fontSize: 15, fontWeight: 'bold', color: '#1F2937' },
    tSub: { fontSize: 12, color: '#6B7280', marginTop: 4 },
    
    dateTag: { backgroundColor: '#FFF', paddingHorizontal: 6, paddingVertical: 2, borderRadius: 5, marginLeft: 8, borderWidth: 1, borderColor: '#DDD' },
    dateTagText: { fontSize: 9, fontWeight: 'bold', color: '#666' },

    actionRow: { flexDirection: 'row', gap: 10 },
    iconBtn: { padding: 10, borderRadius: 12, backgroundColor: '#F0F2FF' },
    pdfBtn: { padding: 5 },
    empty: { textAlign: 'center', marginTop: 30, color: '#9CA3AF', fontWeight: 'bold' }
});

export default StatementScreen;